 name: deploy
 on:
   push:
     branches:
       - 'main'
 jobs:
   build:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v4
       - name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
       - name: Build and push
         uses: docker/build-push-action@v5
         with:
           context: .
           file: ./Dockerfile
           push: true
<<<<<<< HEAD
           tags: ${{ secrets.DOCKERHUB_USERNAME }}/PFG7-Back:latest
=======
           tags: ${{ secrets.DOCKERHUB_USERNAME }}/pfg7-back:latest
>>>>>>> cfbbbc89ee90b6688a5252e2b8bd71c929d7f072
